---

exclude: ^.*\._py$

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending

 - repo: https://github.com/domdfcoding/pre-commit-hooks
   rev: v0.4.0
   hooks:
    - id: requirements-txt-sorter
      args:
       - --allow-git
    - id: check-docstring-first
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup|tests/.*)\.py$
    - id: bind-requirements

 - repo: https://github.com/pre-commit/pygrep-hooks
   rev: v1.10.0
   hooks:
    - id: python-no-eval
    - id: python-use-type-annotations

 - repo: https://github.com/asottile/pyupgrade
   rev: v3.4.0
   hooks:
    - id: pyupgrade
      args:
       - --py36-plus

 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.5.1
   hooks:
    - id: remove-crlf
    - id: forbid-crlf

 - repo: https://github.com/domdfcoding/yapf-isort
   rev: v0.6.0
   hooks:
    - id: yapf-isort
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup|repo_helper/templates/.*)\.(_)?py$
